export const ACCOUNT_TYPE_CODE = {
	STUDENT: 'STUDENT',
	COACH: 'COACH'
} as const;

export const ACCOUNT_TRANSACTION_TYPE = {
	STUDENT_CHARGE: 'STUDENT_CHARGE',
	STUDENT_PAYMENT: 'STUDENT_PAYMENT',
	COACH_CHARGE: 'COACH_CHARGE',
	COACH_PAYMENT: 'COACH_PAYMENT'
};

export const LEDGER_CODE = {
	ACCOUNTS_PAYABLE: 'ACCOUNTS_PAYABLE',
	ACCOUNTS_RECEIVABLE: 'ACCOUNTS_RECEIVABLE',
	COMMISSION: 'COMMISSION',
	CASH: 'CASH',
	BILLING_REVENUE: 'BILLING_REVENUE',
	COACH_INCOME: 'COACH_INCOME'
} as const;

export const ROLES = {
	ADMIN: 'ADMIN',
	COACH: 'COACH',
	CLIENT: 'CLIENT'
};
